version: "3"
services:
  flask:
    container_name: flask_app
    build: ./flask
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_PORT=4000
    ports: 
      - 3000:4000
    depends_on:
      - scraper
    restart: always
    command: python3 main.py
    networks:
      - back-tier
  scraper:
    container_name: scraper
    build: ./scrapper
    command: python3 main.py
    networks:
      - front-tier

networks:
  front-tier: {}
  back-tier: {}